require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/recommended_plans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RecommendedPlan. As you add validations to RecommendedPlan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RecommendedPlan.create! valid_attributes
      get recommended_plans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      recommended_plan = RecommendedPlan.create! valid_attributes
      get recommended_plan_url(recommended_plan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_recommended_plan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      recommended_plan = RecommendedPlan.create! valid_attributes
      get edit_recommended_plan_url(recommended_plan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RecommendedPlan" do
        expect {
          post recommended_plans_url, params: { recommended_plan: valid_attributes }
        }.to change(RecommendedPlan, :count).by(1)
      end

      it "redirects to the created recommended_plan" do
        post recommended_plans_url, params: { recommended_plan: valid_attributes }
        expect(response).to redirect_to(recommended_plan_url(RecommendedPlan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RecommendedPlan" do
        expect {
          post recommended_plans_url, params: { recommended_plan: invalid_attributes }
        }.to change(RecommendedPlan, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post recommended_plans_url, params: { recommended_plan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested recommended_plan" do
        recommended_plan = RecommendedPlan.create! valid_attributes
        patch recommended_plan_url(recommended_plan), params: { recommended_plan: new_attributes }
        recommended_plan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the recommended_plan" do
        recommended_plan = RecommendedPlan.create! valid_attributes
        patch recommended_plan_url(recommended_plan), params: { recommended_plan: new_attributes }
        recommended_plan.reload
        expect(response).to redirect_to(recommended_plan_url(recommended_plan))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        recommended_plan = RecommendedPlan.create! valid_attributes
        patch recommended_plan_url(recommended_plan), params: { recommended_plan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested recommended_plan" do
      recommended_plan = RecommendedPlan.create! valid_attributes
      expect {
        delete recommended_plan_url(recommended_plan)
      }.to change(RecommendedPlan, :count).by(-1)
    end

    it "redirects to the recommended_plans list" do
      recommended_plan = RecommendedPlan.create! valid_attributes
      delete recommended_plan_url(recommended_plan)
      expect(response).to redirect_to(recommended_plans_url)
    end
  end
end
